# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a373fe173f3ac6b795100528d2f48f90f14550cd1e44339d96765e4611ee57de73d325204653e6bee704b299647db2f11739680522a618bc02f704fee0bc3b1f

test:
  secret_key_base: 8c754d3f6b4e11ae3fb47ee274e7828750ac022036f9b333933c1d0604d5601e45000ddec94343bb57e7751d8527ec025a73deafb84d325273c9a710a4ef78e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
